# ─── Ingress ──────────────────────────────────────────────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeforge-monitoring-ingress
  labels:
    app.kubernetes.io/name: codeforge
    app.kubernetes.io/part-of: codeforge
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80
